[2025-03-15T18:00:57.986+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gen_data_daily.calcaulte_fts scheduled__2025-03-13T22:00:00+00:00 [queued]>
[2025-03-15T18:00:58.000+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gen_data_daily.calcaulte_fts scheduled__2025-03-13T22:00:00+00:00 [queued]>
[2025-03-15T18:00:58.000+0000] {taskinstance.py:2171} INFO - Starting attempt 5 of 6
[2025-03-15T18:00:58.020+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): calcaulte_fts> on 2025-03-13 22:00:00+00:00
[2025-03-15T18:00:58.028+0000] {standard_task_runner.py:60} INFO - Started process 2939 to run task
[2025-03-15T18:00:58.033+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'gen_data_daily', 'calcaulte_fts', 'scheduled__2025-03-13T22:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/gen_data_daily.py', '--cfg-path', '/tmp/tmpkzo3pcz7']
[2025-03-15T18:00:58.038+0000] {standard_task_runner.py:88} INFO - Job 15: Subtask calcaulte_fts
[2025-03-15T18:00:58.112+0000] {task_command.py:423} INFO - Running <TaskInstance: gen_data_daily.calcaulte_fts scheduled__2025-03-13T22:00:00+00:00 [running]> on host 1e3bcc32b6c1
[2025-03-15T18:00:58.278+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='longnv' AIRFLOW_CTX_DAG_ID='gen_data_daily' AIRFLOW_CTX_TASK_ID='calcaulte_fts' AIRFLOW_CTX_EXECUTION_DATE='2025-03-13T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-13T22:00:00+00:00'
[2025-03-15T18:00:58.279+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-15T18:00:58.280+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        python /opt/***/external_scripts/2_calculate_features.py 2025-03-14\n        ']
[2025-03-15T18:00:58.299+0000] {subprocess.py:86} INFO - Output:
[2025-03-15T18:01:09.043+0000] {subprocess.py:93} INFO - :: loading settings :: url = jar:file:/opt/spark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-03-15T18:01:09.199+0000] {subprocess.py:93} INFO - Ivy Default Cache set to: /home/***/.ivy2/cache
[2025-03-15T18:01:09.200+0000] {subprocess.py:93} INFO - The jars for the packages stored in: /home/***/.ivy2/jars
[2025-03-15T18:01:09.203+0000] {subprocess.py:93} INFO - org.apache.spark#spark-sql-kafka-0-10_2.12 added as a dependency
[2025-03-15T18:01:09.204+0000] {subprocess.py:93} INFO - io.delta#delta-core_2.12 added as a dependency
[2025-03-15T18:01:09.204+0000] {subprocess.py:93} INFO - org.apache.hadoop#hadoop-aws added as a dependency
[2025-03-15T18:01:09.204+0000] {subprocess.py:93} INFO - com.amazonaws#aws-java-sdk-bundle added as a dependency
[2025-03-15T18:01:09.204+0000] {subprocess.py:93} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-f80bd1ee-aa5d-4116-b50a-df9a35f3ca70;1.0
[2025-03-15T18:01:09.205+0000] {subprocess.py:93} INFO - 	confs: [default]
[2025-03-15T18:01:09.678+0000] {subprocess.py:93} INFO - 	found org.apache.spark#spark-sql-kafka-0-10_2.12;3.4.1 in central
[2025-03-15T18:01:09.783+0000] {subprocess.py:93} INFO - 	found org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.4.1 in central
[2025-03-15T18:01:09.833+0000] {subprocess.py:93} INFO - 	found org.apache.kafka#kafka-clients;3.3.2 in central
[2025-03-15T18:01:09.888+0000] {subprocess.py:93} INFO - 	found org.lz4#lz4-java;1.8.0 in central
[2025-03-15T18:01:09.923+0000] {subprocess.py:93} INFO - 	found org.xerial.snappy#snappy-java;1.1.10.1 in central
[2025-03-15T18:01:09.958+0000] {subprocess.py:93} INFO - 	found org.slf4j#slf4j-api;2.0.6 in central
[2025-03-15T18:01:10.041+0000] {subprocess.py:93} INFO - 	found org.apache.hadoop#hadoop-client-runtime;3.3.4 in central
[2025-03-15T18:01:10.118+0000] {subprocess.py:93} INFO - 	found org.apache.hadoop#hadoop-client-api;3.3.4 in central
[2025-03-15T18:01:10.187+0000] {subprocess.py:93} INFO - 	found commons-logging#commons-logging;1.1.3 in central
[2025-03-15T18:01:10.226+0000] {subprocess.py:93} INFO - 	found com.google.code.findbugs#jsr305;3.0.0 in central
[2025-03-15T18:01:10.250+0000] {subprocess.py:93} INFO - 	found org.apache.commons#commons-pool2;2.11.1 in central
[2025-03-15T18:01:10.282+0000] {subprocess.py:93} INFO - 	found io.delta#delta-core_2.12;2.4.0 in central
[2025-03-15T18:01:10.310+0000] {subprocess.py:93} INFO - 	found io.delta#delta-storage;2.4.0 in central
[2025-03-15T18:01:10.326+0000] {subprocess.py:93} INFO - 	found org.antlr#antlr4-runtime;4.9.3 in central
[2025-03-15T18:01:10.375+0000] {subprocess.py:93} INFO - 	found org.apache.hadoop#hadoop-aws;3.3.2 in central
[2025-03-15T18:01:10.404+0000] {subprocess.py:93} INFO - 	found org.wildfly.openssl#wildfly-openssl;1.0.7.Final in central
[2025-03-15T18:01:10.424+0000] {subprocess.py:93} INFO - 	found com.amazonaws#aws-java-sdk-bundle;1.12.261 in central
[2025-03-15T18:01:10.476+0000] {subprocess.py:93} INFO - :: resolution report :: resolve 1241ms :: artifacts dl 30ms
[2025-03-15T18:01:10.478+0000] {subprocess.py:93} INFO - 	:: modules in use:
[2025-03-15T18:01:10.481+0000] {subprocess.py:93} INFO - 	com.amazonaws#aws-java-sdk-bundle;1.12.261 from central in [default]
[2025-03-15T18:01:10.485+0000] {subprocess.py:93} INFO - 	com.google.code.findbugs#jsr305;3.0.0 from central in [default]
[2025-03-15T18:01:10.486+0000] {subprocess.py:93} INFO - 	commons-logging#commons-logging;1.1.3 from central in [default]
[2025-03-15T18:01:10.489+0000] {subprocess.py:93} INFO - 	io.delta#delta-core_2.12;2.4.0 from central in [default]
[2025-03-15T18:01:10.496+0000] {subprocess.py:93} INFO - 	io.delta#delta-storage;2.4.0 from central in [default]
[2025-03-15T18:01:10.496+0000] {subprocess.py:93} INFO - 	org.antlr#antlr4-runtime;4.9.3 from central in [default]
[2025-03-15T18:01:10.496+0000] {subprocess.py:93} INFO - 	org.apache.commons#commons-pool2;2.11.1 from central in [default]
[2025-03-15T18:01:10.500+0000] {subprocess.py:93} INFO - 	org.apache.hadoop#hadoop-aws;3.3.2 from central in [default]
[2025-03-15T18:01:10.500+0000] {subprocess.py:93} INFO - 	org.apache.hadoop#hadoop-client-api;3.3.4 from central in [default]
[2025-03-15T18:01:10.500+0000] {subprocess.py:93} INFO - 	org.apache.hadoop#hadoop-client-runtime;3.3.4 from central in [default]
[2025-03-15T18:01:10.500+0000] {subprocess.py:93} INFO - 	org.apache.kafka#kafka-clients;3.3.2 from central in [default]
[2025-03-15T18:01:10.501+0000] {subprocess.py:93} INFO - 	org.apache.spark#spark-sql-kafka-0-10_2.12;3.4.1 from central in [default]
[2025-03-15T18:01:10.501+0000] {subprocess.py:93} INFO - 	org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.4.1 from central in [default]
[2025-03-15T18:01:10.501+0000] {subprocess.py:93} INFO - 	org.lz4#lz4-java;1.8.0 from central in [default]
[2025-03-15T18:01:10.501+0000] {subprocess.py:93} INFO - 	org.slf4j#slf4j-api;2.0.6 from central in [default]
[2025-03-15T18:01:10.501+0000] {subprocess.py:93} INFO - 	org.wildfly.openssl#wildfly-openssl;1.0.7.Final from central in [default]
[2025-03-15T18:01:10.501+0000] {subprocess.py:93} INFO - 	org.xerial.snappy#snappy-java;1.1.10.1 from central in [default]
[2025-03-15T18:01:10.501+0000] {subprocess.py:93} INFO - 	:: evicted modules:
[2025-03-15T18:01:10.501+0000] {subprocess.py:93} INFO - 	com.amazonaws#aws-java-sdk-bundle;1.11.1026 by [com.amazonaws#aws-java-sdk-bundle;1.12.261] in [default]
[2025-03-15T18:01:10.501+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-03-15T18:01:10.502+0000] {subprocess.py:93} INFO - 	|                  |            modules            ||   artifacts   |
[2025-03-15T18:01:10.502+0000] {subprocess.py:93} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-03-15T18:01:10.502+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-03-15T18:01:10.502+0000] {subprocess.py:93} INFO - 	|      default     |   18  |   0   |   0   |   1   ||   17  |   0   |
[2025-03-15T18:01:10.502+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-03-15T18:01:10.502+0000] {subprocess.py:93} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-f80bd1ee-aa5d-4116-b50a-df9a35f3ca70
[2025-03-15T18:01:10.502+0000] {subprocess.py:93} INFO - 	confs: [default]
[2025-03-15T18:01:10.513+0000] {subprocess.py:93} INFO - 	0 artifacts copied, 17 already retrieved (0kB/13ms)
[2025-03-15T18:01:11.226+0000] {subprocess.py:93} INFO - 25/03/15 18:01:11 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-03-15T18:01:11.732+0000] {subprocess.py:93} INFO - Setting default log level to "WARN".
[2025-03-15T18:01:11.733+0000] {subprocess.py:93} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2025-03-15T18:01:48.427+0000] {subprocess.py:93} INFO - [Stage 0:>                                                          (0 + 0) / 1][Stage 0:>                                                          (0 + 1) / 1]                                                                                25/03/15 18:01:48 WARN MetricsConfig: Cannot locate configuration: tried hadoop-metrics2-s3a-file-system.properties,hadoop-metrics2.properties
[2025-03-15T18:07:13.241+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2025-03-15T18:07:13.243+0000] {process_utils.py:131} INFO - Sending 15 to group 2939. PIDs of all processes in the group: [2940, 2941, 2949, 2939]
[2025-03-15T18:07:13.243+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 2939
[2025-03-15T18:07:13.244+0000] {taskinstance.py:2451} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-03-15T18:07:13.244+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2025-03-15T18:07:13.268+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 203, in execute
    result = self.subprocess_hook.run_command(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2453, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-03-15T18:07:13.361+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=gen_data_daily, task_id=calcaulte_fts, execution_date=20250313T220000, start_date=20250315T180057, end_date=20250315T180713
[2025-03-15T18:07:13.394+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 15 for task calcaulte_fts (Task received SIGTERM signal; 2939)
[2025-03-15T18:07:13.514+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=2939, status='terminated', exitcode=1, started='18:00:57') (2939) terminated with exit code 1
[2025-03-15T18:07:13.515+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=2940, status='terminated', started='18:00:58') (2940) terminated with exit code None
[2025-03-15T18:07:13.515+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=2941, status='terminated', started='18:00:58') (2941) terminated with exit code None
[2025-03-15T18:07:14.233+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=2949, status='terminated', started='18:01:00') (2949) terminated with exit code None
